### ISSUE TITLE
Station Page: Add song

### ISSUE THREAD

**Issue by pvtri96** [penta-jelly/re-radio#36]
Progress:
- [x] Server
- [x] Client
- [x] Testing

**Comment by dungle1811** [comment]
@pvtri96 I need some APIs for this feature.

1. Search songs:
- Input: string query, quantity
- Output: thumbnail, title

2. Preview song:
- Input: song id
- Output: full of details

**Comment by pvtri96** [comment]
@dungle1811 #49 has included your requirement.
